# Generated by Django 5.1.6 on 2025-03-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_diet_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch_allocation',
            name='fee',
        ),
    ]
