# Generated by Django 5.1.6 on 2025-03-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_workout_name_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees_payment',
            name='TRAINER',
        ),
    ]
