# Generated by Django 5.1.6 on 2025-03-13 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_diet_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='FROM',
            new_name='FROM_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='TO',
            new_name='TO_id',
        ),
    ]
