# Generated by Django 5.1.6 on 2025-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_from_chat_from_id_rename_to_chat_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
