# Generated by Django 5.1.6 on 2025-03-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_diet_date_workout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
    ]
